---
- name: 'Converge'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Converge | apply r_pufky.deb.cron'
      ansible.builtin.include_role:
        name: 'r_pufky.deb.cron'

    - name: 'Converge | apply r_pufky.deb.cron (remove cronjob)'
      ansible.builtin.include_role:
        name: 'r_pufky.deb.cron'
      vars:
        cron_jobs:
          cron_absent:
            state: 'absent'
